# Generated by Django 5.1.4 on 2025-12-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GreenhouseCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('heater', models.BooleanField(default=False)),
                ('ventilation', models.BooleanField(default=False)),
                ('irrigation', models.BooleanField(default=False)),
                ('co2_injector', models.BooleanField(default=False)),
                ('lights', models.BooleanField(default=False)),
                ('tick', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Greenhouse Command',
                'verbose_name_plural': 'Greenhouse Commands',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='GreenhouseReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('soil_moisture', models.FloatField()),
                ('light_intensity', models.FloatField()),
                ('co2_concentration', models.FloatField()),
                ('weather', models.CharField(blank=True, max_length=20, null=True)),
                ('tick', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Greenhouse Reading',
                'verbose_name_plural': 'Greenhouse Readings',
                'ordering': ['-timestamp'],
            },
        ),
    ]
