# Generated by Django 5.1.4 on 2025-12-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(choices=[('heater', 'Heater'), ('ventilation', 'Ventilation'), ('irrigation', 'Irrigation'), ('co2_injector', 'CO2 Injector'), ('lights', 'Lights')], max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Equipment State',
                'verbose_name_plural': 'Equipment States',
            },
        ),
    ]
