# Generated by Django 6.0 on 2025-12-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0002_equipmentstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenhousecommand',
            name='dehumidifier',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='equipmentstate',
            name='equipment_type',
            field=models.CharField(choices=[('heater', 'Heater'), ('ventilation', 'Ventilation'), ('irrigation', 'Irrigation'), ('co2_injector', 'CO2 Injector'), ('lights', 'Lights'), ('dehumidifier', 'Dehumidifier')], max_length=20, unique=True),
        ),
    ]
