# Generated by Django 6.0 on 2025-12-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0003_greenhousecommand_dehumidifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenhousecommand',
            name='light_blinds',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='equipmentstate',
            name='equipment_type',
            field=models.CharField(choices=[('heater', 'Heater'), ('ventilation', 'Ventilation'), ('irrigation', 'Irrigation'), ('co2_injector', 'CO2 Injector'), ('lights', 'Lights'), ('dehumidifier', 'Dehumidifier'), ('light_blinds', 'Light Blinds')], max_length=20, unique=True),
        ),
    ]
